### ISSUE TITLE
[idea] Solid cursor.

### ISSUE THREAD

**Issue by trusktr** [coolwanglu/neovim.as#35]
Can you add an option to change the block cursor from outlined to solid? A good reason to have a solid cursor is because in some terminals an outline cursor indicates the window isn't in focus.

**Comment by raghur** [comment]
+1 came here looking for a `config.cson` option for this...

**Comment by raghur** [comment]
Editing `src\nvim.css` seems to at least to get us partially there...

```
#nvas-cursor {
  position: absolute;
  box-sizing: border-box;
  border: 1px solid;
  background-color: rgba(244,244,244,0.3);
}

```

**Comment by trusktr** [comment]
@raghur Oh wow, I forgot it's just web tech. That was easy!

**Comment by raghur** [comment]
Also, this fixes insert mode cursor

``` css
.insert-mode #nvas-cursor {
  border: 0;
  border-left: 2px solid;
  background-color: transparent;
}
```

**Comment by trusktr** [comment]
I like the transparent cursor:

``` css
#nvas-cursor {
  position: absolute;
  box-sizing: border-box;
  background: rgba(255,255,255,0.3);
}
```

:smile:
